### PR TITLE
All tiles made searchable

### PR DESCRIPTION
**Pull request by lewicki**
New ISearchableText interface to adapt on tiles to make them searchable. All custom tiles may provide their own adapters.
Revisited.

### CODE REVIEW

**Comment by hvelarde** [comment]
@rodfersou could you please help me reviewing this?

@mauritsvanrees @fredvd @djowett opinions?

**Comment by fredvd** [comment]
The option to have multiple tile typees indexable and that you can add indexing for custom (content) tiles is great !!

What concerns me is that for navigation/indexing there are use cases where you don't want the covers to be indexed (fully) because they serve as landing pages and navigation to real content pages on one subject. Covers are most of the time aggregates. When a visitor searches for "my specific page title" you want them to find the content page in the search results, not the 5 covers on which this title is also mentionned.

It's a minor point because this pull request doesn't do the above because only title, desciption and some other general info of 'listy' tiles' is inserted in to the default IsearchableText, not the list items themselves, but adding titles of a list tile to the searchable text for the cover is imho of limited use and might also pollute search results as these are mostly headers like "relevant news", "the latest events" etc. Thing here is that we probably don't want to change behaviour of installed base. 

@lewicki What's your use case for adding title and description of list/collection tiles to the covers searchabletext? Is it a real user demand, or is the ISearchableText mainly there to provide indexing for custom 'content' tiles? then I'd say don't provide adapters for the listy tiles at all or comment them out, then integrators can add them if deemed necessary.

**Comment by lewicki** [comment]
@fredvd There is no usecase. I needed searching functionality for custom tiles so I implemented it in adaptable form. I just provided the example implementation for basic set of tiles. I may revert that part.
Anyone else to comment?

**Comment by mauritsvanrees** [comment]
Seems okay.

**Comment by djowett** [comment]
Hi, FWIW I'm fairly aligned with @fredvd here.  I think it's a good feature to have the option, but the default behavior should be sensible.  It is important that the first search result on a search matching a document / file title should be the document / file itself NOT a cover which has a tile referencing the object.

I think the RichText and Embed tiles should remain & the implementations for other tiles be reverted.
@lewicki can you say what your custom tiles did?

**Comment by hvelarde** [comment]
@lewicki do you mind adding a section on the developers documentation? this seems useful to me.

**Comment by lewicki** [comment]
@djowett Nothing special. Something between basic tile and RichText. Specific customer request.
@hvelarde I'll update documentation as well.
I'll revert some adapters then.

**Comment by djowett** [comment]
@lewicki so similarity to Richtext tile justifies making your custom tile searchable.  Did you make any other tiles searchable for that customer?

**Comment by fredvd** [comment]
@lewicki The decoupling of indexing and tiles is great, until now only richtext was indexed at all and no pluggability. 

Just comment out the registration for other tiles than Rich Text and Basic or remove them except for one that is a commented example for further customisation for other cover integrators. Thanks for the nice addition!

**Comment by hvelarde** [comment]
yes, I agree; after adding the documentation it would be very easy for integrators to activate this feature for more tiles. the documentation can, for instance, take the Basic tile and make it searchable.

to keep backwards compatibility I think we should left only the RichText tile as searchable; let me know if you all agree on that.

**Comment by djowett** [comment]
@hvelarde I'm happy with only the RichText tile searchable.
I'd also be happy with making Embed tile searchable as well, if others thought that sensible.

**Comment by lewicki** [comment]
I updated the code and added some info to developers documentation. I left the adapter for BasicTile, EmbedTile and RichtextTile. Regarding backward compatibility - I would consider not having BasicTile being indexed as a bug not feature.

**Comment by mauritsvanrees** [comment]
Quick remark. I see that Travis fails because of a version conflict for coverage. This is probably caused by a new createcoverage version that is pulled in which now requires a newer coverage. See https://github.com/reinout/createcoverage/pull/1

**Comment by hvelarde** [comment]
@mauritsvanrees yes, I already fixed that on master, but now we have some other tests failing with newer versions of jQuery.

**Pull request merged**
