### PR TITLE
Quality Assurance

### PR DESCRIPTION
**Pull request by hvelarde**
Update code analysis and fix (almost) all errors.

### CODE REVIEW

**Comment by hvelarde** [comment]
@idgserpro do you mind taking care of reviewing this?

**Comment by idgserpro** [comment]
@hvelarde mock 1.3 requires [setuptools>=17.1](https://github.com/testing-cabal/mock/blob/1.3.0/setup.py#L13) but Plone 4.2 setuptools is [0.6c11](https://github.com/plone/buildout.coredev/blob/4.2/versions.cfg#L20). I think only install because used the cache.

**Comment by hvelarde** [comment]
the rest in fine?

**Comment by idgserpro** [comment]
Yes, the rest is ok.

:+1:

**Comment by idgserpro** [comment]
Maybe should be open an issue to fix blind exceptions in the future.

**Pull request merged**
