### PR TITLE
Test last version of plone.api

### PR DESCRIPTION
**Pull request by idgserpro**

### CODE REVIEW

**Comment by idgserpro** [comment]
@hvelarde It seems that plone/plone.api#364 has been fixed in version ```1.8.4``` of ```plone.api``` but ```Plone 4.3.17``` uses [version 1.8.3](https://github.com/plone/buildout.coredev/blob/fbb183db1c49d073d62c8385a5757b7c163291a7/versions.cfg#L277).

But version ```1.8.4``` seems to have a problem with creating Collections [here](https://github.com/collective/collective.cover/blob/5b329590b532c51ade3e5e920d8e6038ff855205/src/collective/cover/tests/utils.py#L22).

**Comment by hvelarde** [comment]
@idgserpro it might be our fault also; please add a test to plone.api demonstrating the issue.

**Comment by idgserpro** [comment]
See: plone/plone.api#410

**Comment by hvelarde** [comment]
I'm already addressing this in #699.

**Pull request closed without merging**
