### PR TITLE
Fredvd fix remove list item

### PR DESCRIPTION
**Pull request by fredvd**
undefined variable in javascript, added let

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by fredvd** [comment]
@hvelarde thanks for the merge. Would it be possible to create a new patch release? This and another fix make the list tile functional again (drag/dropping items & deleting them).

**Comment by hvelarde** [comment]
@idgserpro can you help with the new release? I just make you guys maintainers in PyPI.

**Comment by idgserpro** [comment]
@hvelarde to make the release, we need permission on github too.

**Comment by hvelarde** [comment]
@idgserpro now you have permissions on this repo also; please note that release must be done according this procedure:

https://github.com/collective/collective.lazysizes#releasing-using-zest-releaser

do you mind adding thata same section to the README file of collective.cover?

**Comment by idgserpro** [comment]
@hvelarde thanks! Ok I will add a section to the README.

**Comment by idgserpro** [comment]
@fredvd @hvelarde I created the 2.2.3 release: 

https://pypi.org/project/collective.cover/2.2.3

**Pull request merged**
