### PR TITLE
Upgrade to plone.app.blocks 2.x [#331]

### PR DESCRIPTION
**Pull request by datakurre**
This pull is to see, what Travis thinks about this and discuss about this.

### CODE REVIEW

**Comment by datakurre** [comment]
FYI: I haven't tried upgrading from older c.cover to a c.cover with p.a.blocks 2.0.0, but I don't recall any required changes in p.a.blocks configuration.

**Comment by datakurre** [comment]
@hvelarde Build on Plone 4.2 fails, because p.a.blocks requires Plone 4.3. You added that requirement. Do you remember, what it p.a.blocks required Plone 4.3?

**Comment by datakurre** [comment]
Checked. The layout behavior uses grok-free Dexterity 2.x API for defining the layout fieldset and Dexterity 2.x versions are default only from Plone 4.3 onwards.

Your call. Cover does not need must of it, so it could be refactored with conditional imports to be backwards compatible, if you wish so.

**Comment by hvelarde** [comment]
let's make one more release and then we can drop support for Plone 4.2 in 1.0b2.

do you agree?

**Comment by hvelarde** [comment]
@datakurre I made a rebase; could you please double check to see if I didn't broke anything?

**Comment by datakurre** [comment]
@hvelarde Look OK and tests seem to pass.

**Comment by hvelarde** [comment]
@datakurre what's the status on the new versions of plone.app.tiles and plone.tiles? should we upgrade those also?

**Comment by datakurre** [comment]
@hvelarde Maybe one step at time? plone.app.tiles 1.x -> 2.x includes backwards incompatible tile deletion API change (tile deletion will be through similar URL and form as edit to allow some complex customizations and make it easy to support Plone 5's POST authorization tokens).

**Comment by djowett** [comment]
+1 to "one more release"

**Comment by djowett** [comment]
Can I ask what this upgrade gives to collective.cover?  I'm not questioning doing it, I just want to understand the benefits / impact

**Comment by datakurre** [comment]
It fixes some side effects of c.cover 1.x by enabling the blocks transform only on c.cover views.

Daniel Jowett kirjoitti pe toukokuuta 22 17:47:26 2015 GMT+0300:

**Comment by hvelarde** [comment]
@djowett it fixes #331

**Comment by hvelarde** [comment]
thanks, @datakurre; you rock!

**Pull request merged**
