### PR TITLE
Run RF tests on PhantomJS instead of Firefox

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@datakurre could you please give some advice here? do you know why tests are failing?

**Comment by idgserpro** [comment]
Shouldn't we test on both?

**Comment by datakurre** [comment]
I guess this is because Firefox selenium dependencies are currently really hard, because of each new versions requiring too often both the latest selenium and the latest geckodriver.

@hvelarde PhantomJS may run in mobile window size by default. Do you already have ``Set window size  1200  900`` or similar in the tests?

**Comment by hvelarde** [comment]
@datakurre no, I don't; that's the recommended size? I'll test later.

**Comment by hvelarde** [comment]
@datakurre seems it's not working neither; let me know if you have another idea.

**Comment by idgserpro** [comment]
Why phantomjs instead of chrome? Do you want to get rid of drivers nightmare?

**Comment by hvelarde** [comment]
@idgserpro yes

**Comment by hvelarde** [comment]
superseded by #784

**Pull request closed without merging**
