### PR TITLE
Include a trigger to init patterns in case plone.app.widgets is used

### PR DESCRIPTION
**Pull request by frapell**
If plone.app.widgets is installed and patterns are being used, call the registry scan to initialize them when the edit form popup is opened for a tile

### CODE REVIEW

**Comment by hvelarde** [comment]
any news on this?

**Comment by frapell** [comment]
Unfortunately I don't have enough time to add all requested tests for this. So, I just fixed it as a temporary patch from one of our products.

Also, I ended up doing it slightly different, so you can close this pull, or leave it open as a starting point if someone else wants to pick it up from here.

**Comment by hvelarde** [comment]
I will love to leave it, but I need you to create a branch under this repository and not in the fork to allow modifications from people outside Enfold.

can you do that?

**Comment by frapell** [comment]
Yes, I will create a new branch under collective and put the proper code (not this) later today

**Comment by rodfersou** [comment]
@frapell @fulv I pinned plone.app.widgets to version 1.8.0 with plone 4.3.x matrix and the tile is working fine here, did I test right? or the bug is gone?

**Comment by hvelarde** [comment]
superseded by #575 575

**Pull request closed without merging**
