### PR TITLE
This change observes recommendations

### PR DESCRIPTION
**Pull request by scmos**
This change observes recommendations

### CODE REVIEW

**Comment by idgserpro** [comment]
@scmos another thing. I recommend you always create a branch to do a PR and never do in master.

You can do `git reset --hard` on master of your fork, so that it is the same as here again.

**Comment by scmos** [comment]
> @scmos another thing. I recommend you always create a branch to do a PR and never do in master.
> 
> You can do `git reset --hard` on master of your fork, so that it is the same as here again.

Yes, I will do in future.

**Comment by idgserpro** [comment]
@scmos I think it's better to close this PR and create another from a branch other than the master.

**Comment by idgserpro** [comment]
> You can do git reset --hard on master of your fork, so that it is the same as here again.

Or better.

@hvelarde can you invite @scmos to Collective Organization? I tried but couldn't. Then he can create branches in the `collective/collective.cover` itself.

**Pull request closed without merging**
