### PR TITLE
Upgrade plone.tiles to 1.8.0

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@datakurre seems that someone had disabled the build creation for collective.cover in Travis CI.

seems there only one test broken, the one related with ESI support, but I'm not pretty sure if that ever worked; I'm +1 on removing it if nobody knows how to fix it, as we're not using this feature anywhere.

CC @cleberjsantos @idgserpro

**Comment by idgserpro** [comment]
@hvelarde  Actually there's another broken test:

```
Failure in test Test Basic Tile (test_basic_tile.robot) #issue_637
Traceback (most recent call last):
  File "/home/travis/build/collective/collective.cover/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/collective/collective.cover/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Page should have contained text 'Internal Server Error' but did not
```

**Comment by datakurre** [comment]
So, both of these still pass with tiles 1.6.x?

**Comment by hvelarde** [comment]
@idgserpro I suspect that's a Mandelbug.

@datakurre tests were failing for 1.6.1 also: https://travis-ci.org/collective/collective.cover/builds/159395886

**Comment by idgserpro** [comment]
@hvelarde I restarted the job and the robot error disappear.

**Pull request merged**
