### PR TITLE
use pat-autotoc instead of old formTabbing refs #718

### PR DESCRIPTION
**Pull request by cdw9**
takes care of the JS `tabs()` error, which break most JS on pages for anonymous users.

### CODE REVIEW

**Comment by idgserpro** [comment]
It would be a nice touch to run `rebuild_i18n` since you're adding new strings to the package. `Recent Items` is `Itens recentes` in pt-br, @hvelarde could help with Spanish `*.po`.

**Comment by idgserpro** [comment]
Since js files were modified, an upgradeStep is needed as well (for example https://github.com/collective/collective.cover/blob/master/src/collective/cover/upgrades/v18/configure.zcml#L15).

**Comment by hvelarde** [comment]
@cdw9 thanks! is this for Plone 5 only? did you test if it works also on Plone 4.3?

**Comment by cdw9** [comment]
@hvelarde Sorry, I did not test on 4.3, I was assuming master would be for Plone 5.  This will not work on 4.3. I see there is a plone5 branch, but it hasn't been touched in a couple years. Should I get that updated and use it instead?

@idgserpro There are not new strings, they were just moved, but I missed moving the `i18n:translate=""` with them. I can get that added. Also we won't need to cook the registries since this is only for Plone 5.

**Comment by hvelarde** [comment]
@cdw9 you may base your work in the master branch as we need to keep moving slowly for now.

we don't use collective.cover in Plone 5 and having a versions specific to it will increase the administrative work.

**Comment by cdw9** [comment]
closing PR: I will fix a couple things and resubmit to the `plone5` branch

**Comment by hvelarde** [comment]
@cdw9 please don't use that branch as it's completely outdated and I already implemented many of those things in the master branch.

it's really better to fix things in master as we can't compromise ourselves to maintain 2 branches of this package: we are a very small team with a lot of work to do; please help us on this.

**Pull request closed without merging**
