### PR TITLE
Remove upgrade steps for old, unsupported releases

### PR DESCRIPTION
**Pull request by hvelarde**
Version 1.1b1 is now 3-years old and we are not going to maintain it.

### CODE REVIEW

**Comment by idgserpro** [comment]
Should we bump to 2.x like the discussion we had in https://github.com/collective/sc.social.like/pull/162? Or at least a full 1.8 release?

**Comment by rodfersou** [comment]
I don't like to remove these kind of code because they are some "recipes" that we could use in the future.

How about to transform some of them in functions inserted into ``upgrades/__init__.py`` like the ones to cook CSS and JS?

**Comment by hvelarde** [comment]
@rodfersou AFAIK, I'm not removing that code.

**Comment by rodfersou** [comment]
@hvelarde please read again.. I am suggesting to create new functions from what we learn in the code being removed.

**Comment by hvelarde** [comment]
@rodfersou like what?

**Comment by rodfersou** [comment]
@hvelarde a function to update static resource ID for example

**Comment by rodfersou** [comment]
In the near future we will need to do this when start using webpack in cover.

**Pull request merged**
