### PR TITLE
Fixed too long line.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Goal: test Travis with a minor change.

Travis gives problems on pull request #682, where the tests pass, but the job hangs and gets killed. So let's check with a very minor change, to make sure that it really has nothing to do with the robot test that I added in that pull request.

### CODE REVIEW

**Comment by hvelarde** [comment]
seems it's working… awesome! do we really need to kill the Firefox process besides using the ESR version?

**Comment by hvelarde** [comment]
yes, we need it: https://travis-ci.org/collective/collective.cover/jobs/176685533

**Comment by hvelarde** [comment]
awesome! I'm adding those changes in the other PR to merge it.

**Comment by mauritsvanrees** [comment]
There was one Travis failure even with killing, but that seemed a test that may have been unstable. I restarted that single job and it worked.

It could be that the latest ESR is not needed, and that killing is enough. But it seems good to test with a more recent Firefox.

About an hour ago I restarted a job from the other PR to see if things magically started working there, which would have meant it was all just temporary wrong behavior from Firefox on Travis. But that job ran the tests fine and then kept hanging as well. So it seems killing the process is now really needed.

Note that with normal `pkill` it still failed in one case, but changing it to`pkill -9` helped.

**Pull request closed without merging**
