### PR TITLE
Carousel extra space problem fix #414

### LINKED ISSUE #414: Carousel Tile has incorrect size, style
This is a bad regression from 1.0a7 to 1.0a8.post1.
To reproduce:
1. Run Plone4.3.3 unified installer
2. Add collective.cover=1.0a8.post1 to the eggs section in buildout.cfg
3. run buildout
4. Create Plone site, and add collective.cover
5. Upload 2 images to site
6. Create a cover, empty layout
7. Go to layout tab, add a carousel
8. Go to compose tab, drag the two images uploaded previously into the carousel
9. Go to view tab

Result:  
- The images extend to basically 100% of the page width, but are blurred.
- The dots of the "galleria-thumbnails" are not overlaid on top of the image, but below it

cover8

Expected, from 1.0a7 (this is the result when you repeat the above steps, but replace 1.0a7 in step 2):
- The image is not blurred, and is scaled down to some degree (not sure what the @@images/<UID>.jpeg view does)
- The dots of the "galleria-thumbnails" are on top of the image.

cover7

### PR DESCRIPTION
**Pull request by terapyon**

### CODE REVIEW

**Comment by hvelarde** [comment]
please rebase your branch against master

**Comment by djowett** [comment]
I generally use the following CSS to fix vertical space issues (unless I switch to Cycle2).
It's not obvious, because galleria plays with CSS through JS, but it does work (if hard coded)....

    .cover-carousel-tile .galleria-container {
        height: 320px !important;
    }

**Comment by hvelarde** [comment]
@djowett thanks for your comments!

@agnogueira @ericof what do you think?

**Comment by hvelarde** [comment]
@terapyon any news on this? I can't rebase it as you forked the repo

**Pull request closed without merging**
