### PR TITLE
Issue 588 - After drag and drop implementation, cover breaks if you remove the re…

### LINKED ISSUE #588: After drag and drop implementation, cover breaks if you remove the referenced item in a tile
After the commit https://github.com/collective/collective.cover/commit/adb1a67b27da8657f0b7e099b87dba337c6b04cf, if you normally add a File to a tile in compose view, them remove the File from folder_contents and go to compose again you get

```python
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module grokcore.view.components, line 150, in __call__
  Module grokcore.view.components, line 154, in _render_template
  Module five.grok.components, line 130, in render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/user/Desktop/collective.cover/src/collective/cover/browser/templates/compose.pt
   - Line 33, Column 4
   - Expression: <PathExpr standard:u'layout/render_compose'>
   - Names:
      {'args': (),
       'container': <Cover at /Plone/capa>,
       'context': <Cover at /Plone/capa>,
       'default': <object object at 0xb74ff858>,
       'here': <Cover at /Plone/capa>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xb12fec0c>,
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/capa/compose>,
       'root': <Application at >,
       'static': None,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0xb394e96c>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>,
       'view': <collective.cover.browser.cover.Compose object at 0xb17ace6c>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0xb4300b4c>}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module Products.PageTemplates.Expressions, line 117, in render
  Module collective.cover.layout, line 135, in render_compose
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/user/Desktop/collective.cover/src/collective/cover/layout_templates/pagelayout.pt
   - Line 11, Column 16
   - Expression: <PythonExpr (view.render_section(section, mode))>
   - Names:
      {'args': (),
       'context': <Cover at /Plone/capa>,
       'default': <object object at 0xb74ff858>,
       'loop': {},
       'nothing': None,
       'options': {'mode': 'compose'},
       'repeat': {},
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/capa/compose>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0xb3be6e6c>,
       'view': <collective.cover.layout.PageLayout object at 0xb17712ac>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xb177172c>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.render_section(section, mode))
  Module <string>, line 1, in <module>
  Module collective.cover.layout, line 87, in render_section
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/user/Desktop/collective.cover/src/collective/cover/layout_templates/row.pt
   - Line 35, Column 24
   - Expression: <PythonExpr (view.render_section(child, mode))>
   - Names:
      {'args': (),
       'context': <Cover at /Plone/capa>,
       'default': <object object at 0xb74ff858>,
       'loop': {},
       'nothing': None,
       'options': {'mode': 'compose',
                   'section': {u'children': [{u'children': [{'class': 'tile',
                                                             'css_class': u'tile tile-default',
                                                             u'id': u'a288bf9d-58dd-41f0-b762-6b15bac74a6c',
                                                             'tile-title': u'File Tile',
                                                             u'tile-type': u'collective.cover.file',
                                                             u'type': u'tile'}],
                                              'class': 'cell width-16 position-0',
                                              u'column-size': 16,
                                              u'roles': [u'Manager'],
                                              u'type': u'group'}],
                               'class': 'row',
                               u'type': u'row'}},
       'repeat': {},
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/capa/compose>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0xb3be6fcc>,
       'view': <collective.cover.layout.PageLayout object at 0xb17712ac>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xb14e7bac>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.render_section(child, mode))
  Module <string>, line 1, in <module>
  Module collective.cover.layout, line 89, in render_section
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/user/Desktop/collective.cover/src/collective/cover/layout_templates/group.pt
   - Line 34, Column 28
   - Expression: <PythonExpr (view.render_section(child, mode))>
   - Names:
      {'args': (),
       'context': <Cover at /Plone/capa>,
       'default': <object object at 0xb74ff858>,
       'loop': {},
       'nothing': None,
       'options': {'mode': 'compose',
                   'section': {u'children': [{'class': 'tile',
                                              'css_class': u'tile tile-default',
                                              u'id': u'a288bf9d-58dd-41f0-b762-6b15bac74a6c',
                                              'tile-title': u'File Tile',
                                              u'tile-type': u'collective.cover.file',
                                              u'type': u'tile'}],
                               'class': 'cell width-16 position-0',
                               u'column-size': 16,
                               u'roles': [u'Manager'],
                               u'type': u'group'}},
       'repeat': {},
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/capa/compose>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0xb3bef0cc>,
       'view': <collective.cover.layout.PageLayout object at 0xb17712ac>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xb14e7b4c>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.render_section(child, mode))
  Module <string>, line 1, in <module>
  Module collective.cover.layout, line 103, in render_section
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 405, in do_startTag
  Module zope.tal.talinterpreter, line 482, in attrAction_tal
  Module zope.tales.tales, line 704, in evaluateText
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/user/Desktop/collective.cover/src/collective/cover/layout_templates/tile.pt
   - Line 48, Column 20
   - Expression: <PythonExpr (view.get_content_portal_type(tile_type, tile_id))>
   - Names:
      {'args': (),
       'context': <Cover at /Plone/capa>,
       'default': <object object at 0xb74ff858>,
       'loop': {},
       'nothing': None,
       'options': {'mode': 'compose',
                   'section': {'class': 'tile',
                               'css_class': u'tile tile-default',
                               u'id': u'a288bf9d-58dd-41f0-b762-6b15bac74a6c',
                               'tile-title': u'File Tile',
                               u'tile-type': u'collective.cover.file',
                               u'type': u'tile'},
                   'tile_url': '@@collective.cover.file/a288bf9d-58dd-41f0-b762-6b15bac74a6c'},
       'repeat': {},
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/capa/compose>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0xb3bef12c>,
       'view': <collective.cover.layout.PageLayout object at 0xb17712ac>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xb179076c>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.get_content_portal_type(tile_type, tile_id))
  Module <string>, line 1, in <module>
  Module collective.cover.layout, line 157, in get_content_portal_type
AttributeError: 'NoneType' object has no attribute 'portal_type'
```

The error happens here https://github.com/collective/collective.cover/commit/adb1a67b27da8657f0b7e099b87dba337c6b04cf#diff-37e197e3d8e3a93bbdc7cb51b15f57a3R156: there's an uuid in the tile, but the object that has that uuid doesn't exist anymore.

Don't know what is the best solution here: if obj is None, return None? Say a warning and return None? Throw an exception, but just for the tile (like it happens in the cover view if a tile throws an exception)? Create a subscriber when deleting items to see if there's any reference in tiles? @rodfersou 

This has to be fixed before a new release. The cover isn't broken after removing the item, but `/compose` breaks.

### PR DESCRIPTION
**Pull request by rodfersou**
…ferenced item in a tile

closes #588

### CODE REVIEW

**Comment by hvelarde** [comment]
@idgserpro please check if the problem is fixed

**Comment by idgserpro** [comment]
It fixes the error, but we got a usability problem. The title and description of the item is still shown even after the item was deleted:

selecao_134

It becomes an invalid link

selecao_132

And in the "View" you have a broken link to an inexistent content as well

selecao_135

So the user doesn't know what happened.

If the uuid references something that was deleted, you should set it to `None` like @rodfersou [suggested](https://github.com/collective/collective.cover/issues/588#issuecomment-188784305) to fix this usability problem.

**Comment by hvelarde** [comment]
@rodfersou we need to fix the behavior of the tile to clear it's contents if the uuid does not exists or the object was removed

**Comment by rodfersou** [comment]
@idgserpro we need to think more here.. many tiles can show some information without content associated (if instead of drop content you add a custom Title for example)

**Comment by idgserpro** [comment]
When you say "a tile that shows some information without content associated", then how is this association done instead of uuid? I'm not as familiar as you with the collective.cover internals.

**Comment by hvelarde** [comment]
@idgserpro in fact that's not an usability issue: we should not modify the layout of the cover as a side effect of a user deleting a file; there are 2 additional issues here:

1. to be consistent, the tile should not change its content in any way when a user deletes a file: it should still display the link and the link should lead to a 404 error (the same happens when you link a file using TinyMCE and you delete it); we have no time, neither resources, to fix that now; feel free to open a new issue
1. is link integrity working? the user was warned that the cover object had a relation with the file? if not, please fill a new issue

I'm going to merge this as it fixes the error.

**Comment by idgserpro** [comment]
I agree with your final thoughts, this whole situation needs more thought.

But the issue we opened is indeed fixed, and at least the cover isn't broken anymore. Thanks for the fix.

**Comment by rodfersou** [comment]
@hvelarde green here

**Pull request merged**
