### PR TITLE
Review tile refresh with event

### PR DESCRIPTION
**Pull request by rodfersou**
This is a better way to refresh tile at compose tab without need to reload entire page.

### CODE REVIEW

**Comment by idgserpro** [comment]
Don't forget the upgradeStep since you're changing js resources.

**Comment by rodfersou** [comment]
I'll do it later.. @idgserpro now have other priorities.

**Comment by rodfersou** [comment]
@idgserpro added upgrade step (I hope all tests pass now, good night)

**Comment by rodfersou** [comment]
finally green

**Pull request merged**
