### PR TITLE
Pin plone.tiles to 1.4 

### PR DESCRIPTION
**Pull request by fredvd**
as it was unpinned and the buildout/tests is fetching 1.5.2/latest version from pypi.

### CODE REVIEW

**Comment by hvelarde** [comment]
I think you have to pin it also on the other versions files.

**Comment by fredvd** [comment]
I first wanted to test with the 4.3 and made the pull request to get travis-ci.org working.

Runing bin/test on master locally (which hasn't been touched for a month) currently breaks a number of robot tests for me.

**Comment by fredvd** [comment]
I've restarted the Plone 4.2 test build on travis because it failed, but it's strange: I've only updated versions-4.3.x.cfg, so the Plone 4.2 test build shouldn't be affected and pass like the last succesful build from a month ago on master: https://travis-ci.org/collective/collective.cover/builds/127809733

**Comment by hvelarde** [comment]
I have to take a look later to this to see why is failing.

**Pull request merged**
